[package]
name = "mcp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["rt", "macros"] }
serde = { version = "1.0", features = ["derive"] }
